### ISSUE TITLE
Constrained layout?

### ISSUE THREAD

**Issue by flying-sheep** [scverse/plotting_api#2]
https://github.com/scverse/plotting_api/blob/006d50962383699664c782b2428d6be33c5f63d4/src/plot.py#L11

I think using the constrained layout by default would make most sense: https://matplotlib.org/stable/users/explain/axes/constrainedlayout_guide.html

It’s made exactly for our case of “please just let me do things as declarative as possible and make it work”.

I don‘t know how well it works though.

**Comment by grst** [comment]
Sounds good... I haven't heard of the constrained layout before, and was just using "tight" because it arguably works better than the default.
